# Generated by Django 4.2.6 on 2023-10-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fleet', '0001_initial'),
        ('rental', '0002_alter_rental_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='fleet.vehicle'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('RENTED', 'Rented'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled'), ('RESERVED', 'Reserved'), ('PAST DUE', 'Past Due')], default='CONFIRMED', max_length=20),
        ),
    ]
