# Generated by Django 4.2.6 on 2023-10-23 10:26

from django.db import migrations, models
import django.db.models.deletion
import fleet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(max_length=50, unique=True)),
                ('Brand', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Year', models.DateField()),
                ('Type', models.CharField(choices=[('SEDAN', 'Sedan'), ('COUPE', 'Coupe'), ('SPORTS', 'Sports'), ('STATIONWAGON', 'StationWagon'), ('HATCHBACK', 'HatchBack'), ('CONVERTIBLE', 'Convertible'), ('SUV', 'SUV'), ('MINIVAN', 'MiniVan'), ('PICKUP', 'PickUp Truck')], default='SEDAN', max_length=20)),
                ('License_plate', models.CharField(max_length=7, unique=True)),
                ('milage', models.FloatField()),
                ('fuel_type', models.CharField(default='Diesel', max_length=50)),
                ('fuel_consumption', models.FloatField()),
                ('vehicle_picture', models.ImageField(null=True, upload_to=fleet.models.Vehicle.rename_image)),
                ('is_available', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_done_on', models.DateField(auto_now_add=True)),
                ('repairs', models.TextField()),
                ('next_repair', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='fleet.vehicle')),
            ],
        ),
    ]
