# Generated by Django 4.2.6 on 2023-10-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Year', models.DateField()),
                ('Type', models.CharField(choices=[('SEDAN', 'Sedan'), ('COUPE', 'Coupe'), ('SPORTS', 'Sports'), ('STATIONWAGON', 'StationWagon'), ('HATCHBACK', 'HatchBack'), ('CONVERTIBLE', 'Convertible'), ('SUV', 'SUV'), ('MINIVAN', 'MiniVan'), ('PICKUP', 'PickUp Truck')], default='SEDAN', max_length=20)),
                ('License_plate', models.CharField(max_length=6)),
                ('milage', models.FloatField()),
                ('fuel_consumption', models.FloatField()),
                ('front_picture', models.ImageField(null=True, upload_to='')),
                ('back_picture', models.ImageField(null=True, upload_to='')),
                ('right_picture', models.ImageField(null=True, upload_to='')),
                ('left_picture', models.ImageField(null=True, upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_done_on', models.DateField(auto_now_add=True)),
                ('repairs', models.TextField()),
                ('next_repair', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('Vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
    ]
