# Generated by Django 4.2.6 on 2023-10-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='License_plate',
            field=models.CharField(max_length=7),
        ),
    ]
