# Generated by Django 4.2.6 on 2023-10-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_vehicle_back_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='back_picture',
            field=models.ImageField(null=True, upload_to='static/car_images/<django.db.models.fields.CharField>_back'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='front_picture',
            field=models.ImageField(null=True, upload_to='static/car_images/<django.db.models.fields.CharField>_front'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='left_picture',
            field=models.ImageField(null=True, upload_to='static/car_images/<django.db.models.fields.CharField>_left'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='right_picture',
            field=models.ImageField(null=True, upload_to='static/car_images/<django.db.models.fields.CharField>_right'),
        ),
    ]
