# Generated by Django 4.2.6 on 2023-10-20 13:55

from django.db import migrations, models
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_vehicle_back_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='back_picture',
            field=models.ImageField(null=True, upload_to=fleet.models.Vehicle.rename_image),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='front_picture',
            field=models.ImageField(null=True, upload_to=fleet.models.Vehicle.rename_image),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='left_picture',
            field=models.ImageField(null=True, upload_to=fleet.models.Vehicle.rename_image),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='right_picture',
            field=models.ImageField(null=True, upload_to=fleet.models.Vehicle.rename_image),
        ),
    ]
