# Generated by Django 4.2.6 on 2023-10-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_alter_vehicle_back_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='back_picture',
            new_name='vehicle_picture',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='front_picture',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='left_picture',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='right_picture',
        ),
    ]
