# Generated by Django 4.2.6 on 2023-10-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_rename_back_picture_vehicle_vehicle_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='Vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle'),
        ),
    ]
