# Generated by Django 4.2.6 on 2023-10-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_alter_maintenance_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(default='Diesel', max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='Vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='fleet.vehicle'),
        ),
    ]
