# Generated by Django 4.2.6 on 2023-10-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_vehicle_fuel_type_alter_maintenance_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='License_plate',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='VIN',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
